# Generated by Django 5.1.3 on 2024-11-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
